### ISSUE TITLE
Error on Lunch - version 1.7.2_64Bit

### ISSUE THREAD

**Issue by Ralphh30** [jakepoz/RepDev-downloads#2]
Versions 1.7.2_64Bit - Generating the following error on launch:
Exception in thread "main" java.lang.NoClassDefFoundError: com/repdev/RepDevMain
	at com.repdev.launcher.Launcher.main(Launcher.java:46)
Caused by: java.lang.ClassNotFoundException: com.repdev.RepDevMain
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	
Current Environment:
 - Windows 10 22H2 (64 Bit). 
 - Java 8 Update 371 (64 Bit).

**Comment by thechillman422** [comment]
Hi Ralphh30.  I just noticed your issues report.  Sorry no one monitors issues on this page.  you may want to post your issues on SMUG or on the Source Code page https://github.com/jakepoz/RepDev.  RepDev 1.7.3 was just released.  Please give that a try and post issues on SMUG or on the source code page.  Thanks.
